### ISSUE TITLE
Bug Use constrains: When editing metadata in the advanced metadata editor the following metadata fields cannot be set

### ISSUE THREAD

**Issue by silvadealmeida** [zalf-rdm/geonode#113] opened 2024-06-14 08:31 UTC
Fix advanced metada field Use constrains

**Comment by mwallschlaeger** [comment] 2024-06-14 10:10
undocumented duplicate of https://github.com/zalf-rdm/geonode/issues/112

**Closed by mwallschlaeger** 2024-06-14 10:10 UTC
Labels: bug, UI, Forms, Metadata
