### ISSUE TITLE
Bug Restrictions: When editing metadata in the advanced metadata editor the following metadata fields cannot be set

### ISSUE THREAD

**Issue by silvadealmeida** [zalf-rdm/geonode#117] opened 2024-06-14 08:32 UTC
Fix metadata advanced Restrictions

**Comment by silvadealmeida** [comment] 2024-06-14 08:34
We are moving them to a separate issue waiting for the task force resolution about this item

**Comment by mwallschlaeger** [comment] 2024-06-14 10:10
undocumented duplicate of https://github.com/zalf-rdm/geonode/issues/112

**Closed by mwallschlaeger** 2024-06-14 10:10 UTC
Labels: bug, UI, Forms, Metadata
