### ISSUE TITLE
Bug: Download exceed limit for Finow dataset

### ISSUE THREAD

**Issue by specka** [zalf-rdm/geonode#77] opened 2024-05-16 12:25 UTC

**Comment by specka** [comment] 2024-05-30 08:52
I don't understand, what the bug is about. Could you explain a little bit more? And is this high priority with respect to our "ORD integration" objective?

**Comment by mwallschlaeger** [comment] 2024-05-30 09:43
You opened this bug. Exceeding limits is usually related to the nginx configuration inside `geonode-k8s`

**Comment by mwallschlaeger** [comment] 2024-05-31 06:29
this should be high priority, nevertheless I expect this to be a minor task to fix the issue

**Comment by mwallschlaeger** [comment] 2024-06-14 06:25
as i cannot reproduce which dataset is mentioned here, i'm gonna close this issue for now, as soon as this is happening again, repopen this or another ticket including the dataset id or a link to the dataset

**Closed by mwallschlaeger** 2024-06-14 06:25 UTC
Labels: operations-task

**Comment by specka** [comment] 2024-06-14 07:39
As it cannot be reproduced, and nothing was fixed, I cannot not test it. I put it to "Done" and we have to wait and see, if it happens again.
