### ISSUE TITLE
Non Spatial Data contrib module

### ISSUE THREAD

**Issue by mwallschlaeger** [zalf-rdm/geonode#30] opened 2023-08-31 12:24 UTC
Install an test non spatial data contrib module from 52n

**Comment by mwallschlaeger** [comment] 2024-03-14 13:52
this is now part of the 52N workpackage: see full description here: https://docs.google.com/document/d/1o0FnIbRTXNms3fVepsVAL3WODeBmZkBBcjsbGd8SdE8/edit?usp=sharing

**Comment by mwallschlaeger** [comment] 2024-05-14 08:51
this issue must be seperated into a milestone including multiple issues.

**Comment by specka** [comment] 2024-05-16 13:46
siehe auch #81

**Comment by ridoo** [comment] 2024-06-20 09:06
duplicate of #81

**Closed by ridoo** 2024-06-20 09:06 UTC
Labels: feature, 52N
